import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import Topbar from "@/components/Topbar";
import Clock from "@/components/Clock";
import LastKey from "@/components/LastKey";
import MarketList from "@/components/MarketList";
import Distance from "../components/strava/Distance"
import IpInfo from "../components/IpInfo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bubbleFont = localFont({
  src: "./fonts/bubblefont.woff2",
  variable: "--font-bubble",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${bubbleFont.variable} antialiased h-screen flex flex-col`}
      >
        {/* Header persists across routes */}
        <div className="sticky top-0 z-50">
          <Topbar>
            <Clock />
            <h1 className="text-sm select-none font-geist-mono p-5.5 mx-auto">
              <IpInfo />
              <MarketList />
              <Distance />
            </h1>
            <LastKey />
          </Topbar>
        </div>

        {/* Page content fills remaining height under header */}
        <main className="flex-1 min-h-0 overflow-auto">{children}</main>
      </body>
    </html>
  );
}
